# Database configuration
spring:
  application:
    name: KazerneMediaPLayer
  datasource:
    url: jdbc:mysql://localhost:3306/mediaplayerdb
    username: chef
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQLLegacyDialect

  # Multipart file upload configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

# Media configuration
media:
  upload-dir: D:\\KazerneMediaPlayer Songs 2024

# Server configuration
server:
  port: 8080
