spring:
  application:
    name: KazerneMediaPLayer
  datasource:
    url: jdbc:mysql://localhost:3306/mediaplayerdb
    username: chef
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /media/**

  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Multipart file upload configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB
  web:
    resources:
      static-locations: file:///D:/KazerneMediaPlayer Songs 2024/

# Add the secret key for streaming security token generation
streaming:
  secret:
    key: your-secret-key
  token:
    expiry:
      seconds: 3600

# Media configuration
media:
  upload-dir: D:/KazerneMediaPlayer Songs 2024

# JWT configuration
jwt:
  secret: your_jwt_secret_key
  expiration: 86400000  # or set your desired expiration time in milliseconds
  refreshExpiration: 86400000  # 1 day

# Server configuration
server:
  port: 8080
