spring:
  application:
    name: KazerneMediaPLayer
  datasource:
    url: jdbc:mysql://localhost:3306/mediaplayerdb
    username: chef
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /media/**

  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Multipart file upload configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  web:
    resources:
      static-locations: file:///D:/KazerneMediaPlayer Songs 2024/

# Media configuration
media:
  upload-dir: D:/KazerneMediaPlayer Songs 2024

# JWT configuration
jwt:
  secret: your_jwt_secret_key
  expiration: 3600 # or set your desired expiration time in seconds

# Server configuration
server:
  port: 8080
